# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha', models.DateField(auto_now_add=True, unique_for_date='fecha', verbose_name='registro')),
            ],
        ),
        migrations.CreateModel(
            name='OtraVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='registro')),
            ],
        ),
        migrations.CreateModel(
            name='OtroGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='registro')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha', models.DateField(auto_now_add=True, unique_for_date='fecha', verbose_name='registro')),
            ],
        ),
    ]
